{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gophprofile.fullname" . }}-migrate
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit }}
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        {{- include "gophprofile.podSecurityContext" . | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "gophprofile.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./migrate", "-direction=up"]
          securityContext:
            {{- include "gophprofile.containerSecurityContext" . | nindent 12 }}
          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          env:
            {{- range $key, $value := .Values.config }}
            - name: {{ $key }}
              value: {{ $value | toString | quote }}
            {{- end }}
          {{- else }}
          env:
            {{- range $key, $value := .Values.config }}
            - name: {{ $key }}
              value: {{ $value | toString | quote }}
            {{- end }}
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              value: {{ $value | toString | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.migrate.resources | nindent 12 }}
          {{- include "gophprofile.tmpVolumeMount" . | nindent 10 }}
      {{- include "gophprofile.tmpVolume" . | nindent 6 }}
{{- end }}
