{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
