{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gophprofile.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.config.METRICS_PATH | default "/metrics" | quote }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
